[package]
name = "sirius"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["thatmagicalcat <thatmagicalcat@hotmail.com>"]
description = "A binary serialization/deserialization library"

[dependencies]
