[package]
name = "sirius-macros"
version = "0.1.1"
edition = "2024"
license = "MIT"
authors = ["thatmagicalcat <thatmagicalcat@hotmail.com>"]
description = "Macros for sirius"

[dependencies]
proc-macro2 = "1.0.94"
quote = "1.0.40"
syn = "2.0.100"

[lib]
proc-macro = true
